import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

// if i want the scrolling type of portfolio then everything just goes here

export default function Home() {
  return (
    <>
      <Head>
        <title>Selam Beyene Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Selam&apos;s Portfolio</h1>
    </>
  )
}  