import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import { Container, Row, Col, Card } from 'react-bootstrap';
import Navbar from '@/components/Navbar';
import Projects from '@/components/Projects';
// import BackgroundAnimation from '@/components/BackgroundAnimation';
import styles from '../styles/BackgroundAnimation.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Selam Beyene Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css" />
          
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <BackgroundAnimation /> */}

      {/* Header Section */}
      <Navbar />

      <Container className="bg-dark text-light my-5" id='landing'>
        <Row>
          {/* <Col md={6}>
            <Image src="/headshot.png" alt="My Headshot" width={200} height={200} />
          </Col> */}
          {/* <Col md={6}> */}
          <span className='text-center'>
            <h1 className={`text-center ${styles['animated-heading']}`}>Selam Beyene</h1>
            <h3>Full Stack Software Engineer</h3>
          </span>
          {/* </Col> */}
        </Row>
      </Container>

      {/* About Me Section */}
      <Container className="bg-dark text-light my-5" id="about">
        <Row>
          {/* <Col md={6}> */}
            <h2 className='text-center'>About Me</h2>
            <Col md={6}>

            </Col>
            <Col md={6}>
            <p>
            Hey there! I'm Selam Beyene, a junior software engineer on a winding journey that started with numbers, zigzagged through day trading, and landed me in the exciting realm of coding. Armed with a finance degree from San Jose State University, I initially set out to empower folks with financial wisdom. But a detour into day trading and a full-stack software engineering bootcamp changed the game.
            </p>
            <p>
            Along the way, I taught myself the ropes of UX/UI design and stock trading. College life saw me co-founding a non-profit, supporting the East African diaspora, and kickstarting the Ethiopian & Eritrean Student Conference—because collaboration knows no bounds!
            </p>
            <p>
            Beyond the tech buzz, I'm all about soaking in the vibes of different places and cheering on my beloved Golden State Warriors. Oh, and this year, I proudly claimed victory in my very first fantasy football league!
            </p>
            <p>
            Now, with a bag full of skills and a passion for problem-solving, I'm stoked to dive into software engineering. Let's chat! I bring not just technical prowess but a genuine enthusiasm for creative collaboration. Together, let's craft something truly awesome!
            </p>
            </Col>
          {/* </Col> */}
        </Row>
      </Container>

      <Container className="bg-dark text-light my-5 text-center " id="skills">
        <Row>
            <h2>Skills</h2>
          <Col>
            <h4>Languages:</h4>
            <ul style={{ listStyleType: 'none', padding: 0 }}>
              <li>Python</li>
              <li>Javascript</li>
              <li>HTML</li>
              <li>CSS</li>
              <li>SQL</li>
            </ul>
          </Col>
          <Col>
            <h4>Frameworks/Libraries:</h4>
            <ul style={{ listStyleType: 'none', padding: 0 }}>
              <li>React</li>
              <li>Django</li>
              <li>Mongoose</li>
              <li>Node.js</li>
              <li>Next.js</li>
            </ul>
          </Col>
        </Row>
      </Container>

      {/* Projects Section */}
      <Container className="bg-dark text-light py-5" id="projects">
        <span className='text-center'>
          <h1 className=' mb-4'>Projects</h1>
        </span>
        <Projects />
      </Container>

      {/* Contact Me Section */}
      <Container className="bg-secondary text-white text-center py-5" id="contact">
        <h2>Contact Me:</h2>
        {/* Add your contact form or information here */}
      </Container>
    </>
  );
}
